[theme]
primaryColor = "#0047AB"  
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#D0E6F7"
textColor = "#002D62"
font = "sans serif"


[server]
enableXsrfProtection = false
enableCORS = false

[multipage]
enabled = true



#Gets rid of the ugly navigations on top left
#[client]
#showSidebarNavigation = false
